version: 2 
jobs: 
  build: 
    
    working_directory: ~/webapp-service 

    docker: 
      - image: circleci/openjdk:8-jdk-stretch 
    steps: 

      - checkout 
      - restore_cache:     
          key: webapp-service-{{ checksum "pom.xml" }}     
      - run: mvn dependency:go-offline    
      - save_cache: 
          paths:
            - ~/.m2
          key: webapp-service-{{ checksum "pom.xml" }}      
      - run: mvn package 
      - store_test_results: 
          path: target/surefire-reports   
      - store_artifacts: 
          path: target/webapp-0.0.1-SNAPSHOT.war
      
  pr_check:
      working_directory: ~/webapp-service 
      docker:
         - image: circleci/openjdk:8-jdk-stretch
      steps:
         - checkout
         - restore_cache:
            key: webapp-service-{{ checksum "pom.xml" }}
         - run: mvn dependency:go-offline
         - save_cache:
              paths:
              - ~/.m2
         - run: mvn package
         - store_test_results:
             path: target/surefire-reports
         - store_artifacts:
              path: target/webapp-0.0.1-SNAPSHOT.war
      
   
workflows:
 version: 2
 pr-check:
    jobs:
      - pr_check
 build_deploy:
    jobs:
      - build
#        filters:
#            branches:
#              only: master

      