version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    working_directory: ~/webapp-service
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    
    steps:
    - checkout
    - restore_cache:
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.jar
  pr_check:
    working_directory: ~/webapp-service
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    steps:
    - checkout
    - restore_cache:
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.jar
    environment:
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      # - aws-s3/sync:
      #     from: target
      #     overwrite: true
      #     to: "s3://codedeploy.keshavkaanth.tld"
      - aws-s3/copy:
          from: target/webapp-0.0.1-SNAPSHOT.jar
          to: "s3://codedeploy.keshavkaanth.tld"
workflows:
  version: 2
  pr-check:   
    jobs:
    - pr_check
    - deploy:
        requires:
             - pr_check
  build_deploy:
    jobs:
    - build:
        filters:  
            branches:
              only:  
                - master
