version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-code-deploy: circleci/aws-code-deploy@1.0.1

jobs:
  build:
    working_directory: ~/webapp-service
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    - image: 'cimg/python:3.6'
    steps:
    - checkout
    - restore_cache:
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.jar
  pr_check:
    working_directory: ~/webapp-service
    docker:
    - image: circleci/openjdk:8-jdk-stretch
    steps:
    - checkout
    - restore_cache:
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: webapp-service-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports
    - store_artifacts:
        path: target/webapp-0.0.1-SNAPSHOT.jar
    - run: 
        name: Zip files
        command:
         BUILD_COUNTER=env_CIRCLE_BUILD_NUM
         zip -r ${BUILD_COUNTER}_webapp-server.zip *
    - aws-s3/copy:
        from: ${BUILD_COUNTER}_webapp-server.zip
        to: "s3://codedeploy.keshavkaanth.tld"

workflows:
  version: 2.1
  pr-check:   
    jobs:
    - pr_check
    - aws-code-deploy/deploy:
        application-name:   csye6225-webapp
        deployment-group: csye6225-webapp-deployment
        service-role-arn: arn:aws:iam::479623124360:role/Code-Deploy
        bundle-bucket: codedeploy.keshavkaanth.tld
        bundle-key: ${BUILD_COUNTER}_webapp-server.zip
  build_deploy:
    jobs:
    - build:
        filters:  
            branches:
              only:  
                - master
